name: NodeJS with Webpack

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
          npm install -D webpack-cli

      - name: Build
        run: npx webpack

      - name: Run Unit Tests
        run: npm test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
              badges-directory: .github/badges
              generate-coverage-badge: true
              coverage-badge-filename: jacoco.svg
              generate-branches-badge: true
              branches-badge-filename: branches.svg
              jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Check badge creation
        run: ls -l .github/badges

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updated JaCoCo badges'
          add: '.github/badges/*.svg'

      - name: Show test results
        run: cat build/reports/jacoco/test/jacocoTestReport.csv

      


