name: NodeJS with Webpack

on:
  push:
    branches: [ "SUN" ]
  pull_request:
    branches: [ "SUN" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
          npm install -D webpack-cli

      - name: Build
        run: npx webpack

      - name: Run Unit Tests
        run: npm test
